### PR TITLE
Updates?

### PR DESCRIPTION
**Pull request by twistloop**

### CODE REVIEW

**Comment by erfanoabdi** [comment]
Keep $2

**Comment by twistloop** [comment]
if [[ -n $2 ]]; then
    GIT_OAUTH_TOKEN=$2
elif [[ -f ".githubtoken" ]]; then
    GIT_OAUTH_TOKEN=$(cat .githubtoken)

We already set the value of $2 in the variable

**Comment by erfanoabdi** [comment]
ok cool

**Comment by twistloop** [comment]
Should I merge?

**Comment by kacskrz** [comment]
Yeah, should be OK.

**Pull request merged**
